name: "Manual build and Scan"
on: workflow_dispatch

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v4.1.6
            -   name: Set up JDK
                uses: ./.github/actions/java-setup
                with:
                    cache: 'maven'
            -   name: Set up Node.js
                uses: actions/setup-node@v3
                with:
                  node-version: '22'
            -   name: Build with Maven
                run: mvn --no-transfer-progress verify
            -   name: Install Aikido CI API Client
                run: npm install --global @aikidosec/ci-api-client
            -   name: Run Aikido Scan
                run: aikido-api-client scan-release ${{ github.event.repository.name }} $GITHUB_SHA --apikey ${{ secrets.AIKIDO_CLIENT_API_KEY }} --fail-on-sast-scan --fail-on-iac-scan --fail-on-secrets-scan
